import type { CollectibleStamp } from "./types";

export const STAMP_COLLECTION: readonly CollectibleStamp[] = [
  {
    id: "stamp_morning_brew",
    nameEn: "Artisan Dripper 1924",
    nameRu: "Артизанская Воронка 1924",
    nameDe: "Handfilter-Marke 1924",
    theme: "Ritual",
    rarity: "common",
    icon: "☕",
    color: "#df9f43",
    provenanceEn: "Found tucked inside the morning ledger of a quiet Viennese cafe.",
    provenanceRu: "Найдена среди страниц утренней бухгалтерской книги венской кофейни.",
    provenanceDe: "Gefunden im Hauptbuch eines traditionsreichen Wiener Kaffeehauses.",
  },
  {
    id: "stamp_raven_seal",
    nameEn: "Imperial Raven Post",
    nameRu: "Имперская Почта Ворона",
    nameDe: "Kaiserliche Rabenpost",
    theme: "Correspondence",
    rarity: "common",
    icon: "🪶",
    color: "#aa9987",
    provenanceEn: "Used by northern couriers who crossed the mountain passes before sunrise.",
    provenanceRu: "Печать северных курьеров, пересекавших горные перевалы до рассвета.",
    provenanceDe: "Von Nordkurieren verwendet, die vor Tagesanbruch die Gebirgspässe querten.",
  },
  {
    id: "stamp_midori_compass",
    nameEn: "Kyoto Traveler Rose",
    nameRu: "Роза Ветров Киото",
    nameDe: "Kyoto-Kompassrose",
    theme: "Travel",
    rarity: "uncommon",
    icon: "🧭",
    color: "#60b278",
    provenanceEn: "Stamped on a traveler notebook that journeyed from Osaka to Hokkaido.",
    provenanceRu: "Оттиск из дорожного дневника, прошедшего путь от Осаки до Хоккайдо.",
    provenanceDe: "Abgestempelt in einem Reisetagebuch auf der Route von Osaka nach Hokkaido.",
  },
  {
    id: "stamp_ink_well",
    nameEn: "Scribe Obsidian Well",
    nameRu: "Обсидиановая Чернильница",
    nameDe: "Obsidian-Tintenfass",
    theme: "Archival",
    rarity: "uncommon",
    icon: "🖋️",
    color: "#a58ded",
    provenanceEn: "Preserved in the Guild Vault. The dark ink inside never seems to dry.",
    provenanceRu: "Хранится в архиве Гильдии. Чернила внутри не высыхают уже сто лет.",
    provenanceDe: "Im Gildengewölbe verwahrt. Die Tinte darin trocknet niemals ein.",
  },
  {
    id: "stamp_flawless_sun",
    nameEn: "The Flawless Dawn",
    nameRu: "Безупречный Рассвет",
    nameDe: "Makellose Morgensonne",
    theme: "Mastery",
    rarity: "rare",
    icon: "☀️",
    color: "#f3cb65",
    provenanceEn: "Awarded only to archivists who decipher a dispatch without a single error.",
    provenanceRu: "Вручается архивариусам, расшифровавшим депешу без единой ошибки.",
    provenanceDe: "Verliehen für das fehlerfreie Lösen einer archivierten Depesche.",
  },
  {
    id: "stamp_iron_contract",
    nameEn: "The Iron Contract",
    nameRu: "Железный Контракт",
    nameDe: "Der Eiserne Vertrag",
    theme: "Courage",
    rarity: "rare",
    icon: "⚔️",
    color: "#c84635",
    provenanceEn: "Sealed with blackened wax. Proof of victory in a high-stakes Sudden Death trial.",
    provenanceRu: "Скреплена чёрным сургучом. Знак победы в рискованном испытании Sudden Death.",
    provenanceDe: "Mit schwarzem Wachs besiegelt. Beweis des Mutes in einem Sudden-Death-Kontrakt.",
  },
  {
    id: "stamp_gold_charter",
    nameEn: "The Grand Sovereign Charter",
    nameRu: "Великая Золотая Хартия",
    nameDe: "Große Goldene Urkunde",
    theme: "Prestige",
    rarity: "mythic",
    icon: "👑",
    color: "#ffd700",
    provenanceEn: "The highest seal of the Guild. Reflects light with authentic gold-leaf brilliance.",
    provenanceRu: "Высшая печать Гильдии. Переливается на свету оттиском сусального золота.",
    provenanceDe: "Das höchste Siegel der Gilde. Schimmert im Licht wie reines Blattgold.",
  },
  {
    id: "stamp_botanical_fern",
    nameEn: "Silver Fern Herbarium",
    nameRu: "Серебряный Папоротник",
    nameDe: "Silberfarn-Herbarium",
    theme: "Botanica",
    rarity: "uncommon",
    icon: "🌿",
    color: "#7bc88f",
    provenanceEn: "Pressed between pages of an eighteenth-century botanical taxonomy.",
    provenanceRu: "Засушен между страниц ботанического каталога восемнадцатого века.",
    provenanceDe: "Gepresst zwischen den Seiten eines botanischen Werkes des 18. Jahrhunderts.",
  },
  {
    id: "stamp_palimpsest",
    nameEn: "The Dual Palimpsest",
    nameRu: "Двусторонний Палимпсест",
    nameDe: "Das Doppel-Palimpsest",
    theme: "Mystery",
    rarity: "mythic",
    icon: "📜",
    color: "#d4af37",
    provenanceEn: "An ancient parchment bearing two orthogonal layers of script revealed only by folding.",
    provenanceRu: "Древний пергамент с двумя ортогональными слоями текста, открывающимися при переворачивании листа.",
    provenanceDe: "Ein uraltes Pergament mit zwei orthogonalen Schriftlagen, die sich beim Wenden enthüllen.",
  },
];

export const SEALS = [
  { id: "seal_raven", label: "Raven Crest", labelRu: "Герб Ворона", labelDe: "Raben-Wappen", icon: "🦅" },
  { id: "seal_compass", label: "Compass Rose", labelRu: "Роза Ветров", labelDe: "Kompassrose", icon: "🧭" },
  { id: "seal_keyhole", label: "Golden Keyhole", labelRu: "Золотая Скважина", labelDe: "Goldenes Schlüsselloch", icon: "🗝️" },
  { id: "seal_owl", label: "Nocturnal Owl", labelRu: "Ночная Сова", labelDe: "Nachteule", icon: "🦉" },
  { id: "seal_laurel", label: "Imperial Laurel", labelRu: "Имперский Лавр", labelDe: "Kaiserlicher Lorbeer", icon: "🌿" },
  { id: "seal_palimpsest", label: "Dual Archival Seal", labelRu: "Двойная Печать Архива", labelDe: "Doppeltes Archiv-Siegel", icon: "📜" },
];

export const NIBS = [
  { id: "nib_brass", label: "Brass Italic 1.1mm", labelRu: "Латунное 1.1 мм", labelDe: "Messing Italic 1.1mm", icon: "✒️" },
  { id: "nib_obsidian", label: "Obsidian Fine Point", labelRu: "Обсидиановое тонкое", labelDe: "Obsidian-Feinfeder", icon: "🖋️" },
  { id: "nib_silver", label: "Silver Flex 14K", labelRu: "Серебряное Flex 14K", labelDe: "Silber-Flex 14K", icon: "🖊️" },
  { id: "nib_glass", label: "Murano Glass Dip Pen", labelRu: "Муранское стекло", labelDe: "Murano-Glasfeder", icon: "💎" },
];

export const TITLES = [
  { id: "title_truths", labelEn: "Keeper of Small Truths", labelRu: "Хранитель малых истин", labelDe: "Hüter der kleinen Wahrheiten" },
  { id: "title_connections", labelEn: "Cartographer of Connections", labelRu: "Картограф связей", labelDe: "Kartograph der Verbindungen" },
  { id: "title_unbroken", labelEn: "The Unbroken Hand", labelRu: "Непоколебимая рука", labelDe: "Die ruhige Hand" },
  { id: "title_iron_scribe", labelEn: "The Iron Scribe", labelRu: "Железный писец", labelDe: "Der eiserne Schreiber" },
  { id: "title_grand_archivist", labelEn: "Grand Master Archivist", labelRu: "Верховный архивариус", labelDe: "Großmeister-Archivar" },
];
